/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData toiletries = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addperson = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stall = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bakery = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cleaning = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData canned = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beverages = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData conceptlist = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dairy = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dry = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData familylist = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expenses = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fish = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frozen = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meat = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mylist = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pantry = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pet = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scheduled = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData produce = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
