# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [master]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: flutter build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.5.3"
    steps:
    - uses: actions/checkout@v3
    #- name: Install requirements
      #run: pip install pytest coverage pytest-cov
    #- name: Run tests and collect coverage
      #run: pytest --coverage .
    - name: Codecov
      uses: codecov/codecov-action@v3.1.0
    #- name: Code Coverage Report
      #uses: romeovs/lcov-reporter-action@v0.2.16
    #- name: Upload code coverage to codecov
      #uses: codecov/codecov-action@v3.1.0
      #with:
        #token: ${{secrets.CODECOV_TOKEN}}
        #version: "v0.1.15"
        #files: coverage/lcov.info
        #flags: js_open_source
        #name: memoria
        #verbose: true
        #lcov-file: ./coverage/lcov.info
    #- uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
    - run: flutter pub get
    #- run: flutter analyze
    - run: flutter test
    - name: Upload coverage reports to Codecov
      run: |
        # Replace `linux` below with the appropriate OS
        # Options are `alpine`, `linux`, `macos`, `windows`
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}
        cat codecov.yml | curl --data-binary @- https://codecov.io/validate
    - run: flutter build apk
    #- run: flutter build appbundle
